name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
   
      - name: Skip Deployment
        run: |
          if [[ $SKIP_DEPLOYMENT == "true" ]]; then
            echo "Skipping deployment..."
            exit 0
          fi
      
      - run: npm ci && npm run build
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAME_OF_THRONE_6CA95 }}'
          channelId: live
          projectId: game-of-throne-6ca95
